# Generated by Django 4.2.1 on 2023-07-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='static/upload'),
        ),
    ]
